apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleweb
  namespace: test
  labels:
    app: simpleweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simpleweb
  template:
    metadata:
      labels:
        app: simpleweb
    spec:
      containers:
      - name: simpleweb
        image: yeasy/simple-web:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simpleweb-service
spec:
  selector:
    app: simpleweb
  ports:
    - port: 80
      targetPort: 80
  externalTrafficPolicy: Local
  type: LoadBalancer
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: test-ingress
  namespace: test
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/cors-allow-headers: X-Forwarded-For
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: site.domain.tld
      http:
        paths:
          - path: /
            backend:
              serviceName: simpleweb-service
              servicePort: 80
status:
  loadBalancer:
    ingress:
      - {}
---
